### ISSUE TITLE
Repository Management | Epic for housekeeping Management

### ISSUE THREAD

**Issue by arjunumenon** [pnp/copilot-prompts#14]
This is an issue that is created as an Epic that will have a list of tasks that could be implemented for the basic repository housekeeping. We will be adding the Task list and subsequent issues will be created for each.

We will keep on adding the task list when 

### Task List

- [ ] Add Flags for Managing the Contributions and Tracking #15 
- [ ] Add templates for issues so that sample details can be collected in a Form that will be easy for the end users #16 
- [ ] Template for PR Creation so that we will have a standard PR Template #17
